---
- name: Create application directory
  file:
    path: /opt/wordpress
    state: directory

- name: Pull WordPress Docker image
  docker_image:
    name: wordpress
    source: pull

- name: Run WordPress container
  docker_container:
    name: wordpress
    image: wordpress
    state: started
    restart_policy: always
    ports:
      - "8080:80"